from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculs_Geodisiques(object):
    def setupUi(self, Calculs_Geodisiques):
        Calculs_Geodisiques.setObjectName("Calculs_Geodisiques")
        Calculs_Geodisiques.setEnabled(True)
        Calculs_Geodisiques.resize(818, 615)
        Calculs_Geodisiques.setFixedSize(self , 818, 615)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Calculs_Geodisiques.sizePolicy().hasHeightForWidth())
        Calculs_Geodisiques.setSizePolicy(sizePolicy)
        Calculs_Geodisiques.setAccessibleName("")
        Calculs_Geodisiques.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(Calculs_Geodisiques)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 831, 561))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(0, 0, 811, 21))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setMouseTracking(True)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(0, 30, 811, 511))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_1.setEnabled(True)
        self.lineEdit_1.setGeometry(QtCore.QRect(68, 43, 201, 22))
        self.lineEdit_1.setToolTip("")
        self.lineEdit_1.setAccessibleName("")
        self.lineEdit_1.setInputMask("")
        self.lineEdit_1.setText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(68, 78, 201, 22))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(560, 45, 211, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(560, 80, 211, 22))
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(480, 80, 51, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_6.setAcceptDrops(False)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setLineWidth(4)
        self.label_6.setMidLineWidth(2)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(470, 45, 61, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_7.setAcceptDrops(False)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setLineWidth(23)
        self.label_7.setMidLineWidth(2)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 77, 41, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_8.setAcceptDrops(False)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setLineWidth(4)
        self.label_8.setMidLineWidth(2)
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 42, 40, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_9.setAcceptDrops(False)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setLineWidth(4)
        self.label_9.setMidLineWidth(2)
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(530, 420, 241, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 420, 241, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(12, 143, 45, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_10.setAcceptDrops(False)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setLineWidth(4)
        self.label_10.setMidLineWidth(2)
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 150, 171, 21))
        self.lineEdit_5.setToolTip("")
        self.lineEdit_5.setAccessibleName("")
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 230, 231, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(90, 230, 46, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_11.setAcceptDrops(False)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setLineWidth(4)
        self.label_11.setMidLineWidth(2)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(90, 275, 43, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_12.setFont(font)
        self.label_12.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_12.setAcceptDrops(False)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setLineWidth(4)
        self.label_12.setMidLineWidth(2)
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setScaledContents(False)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(506, 147, 16, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(150, 270, 231, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(30, 5, 581, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        font.setUnderline(False)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(250, 150, 561, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        font.setUnderline(False)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(420, 230, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(420, 280, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setGeometry(QtCore.QRect(480, 230, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        font.setUnderline(False)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame)
        self.label_38.setGeometry(QtCore.QRect(480, 280, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        font.setUnderline(False)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_55 = QtWidgets.QLabel(self.frame)
        self.label_55.setGeometry(QtCore.QRect(270, 170, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        font.setUnderline(False)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.frame)
        self.label_56.setGeometry(QtCore.QRect(0, 360, 211, 131))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap(":/icone/Earth_ellipsoid.png"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.label_39 = QtWidgets.QLabel(self.frame)
        self.label_39.setGeometry(QtCore.QRect(480, 330, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        font.setUnderline(False)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(90, 325, 43, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_24.setFont(font)
        self.label_24.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_24.setAcceptDrops(False)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_24.setLineWidth(4)
        self.label_24.setMidLineWidth(2)
        self.label_24.setTextFormat(QtCore.Qt.RichText)
        self.label_24.setScaledContents(False)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setWordWrap(False)
        self.label_24.setObjectName("label_24")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(150, 320, 231, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icone/icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_2 = QtWidgets.QFrame(self.tab_4)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 811, 271))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 45, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_13.setFont(font)
        self.label_13.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_13.setAcceptDrops(False)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setLineWidth(4)
        self.label_13.setMidLineWidth(2)
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setScaledContents(False)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setEnabled(True)
        self.lineEdit_6.setGeometry(QtCore.QRect(70, 80, 51, 31))
        self.lineEdit_6.setToolTip("")
        self.lineEdit_6.setAccessibleName("")
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 45, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_14.setFont(font)
        self.label_14.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_14.setAcceptDrops(False)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_14.setLineWidth(4)
        self.label_14.setMidLineWidth(2)
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setScaledContents(False)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setWordWrap(False)
        self.label_14.setObjectName("label_14")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_8.setEnabled(True)
        self.lineEdit_8.setGeometry(QtCore.QRect(140, 80, 51, 31))
        self.lineEdit_8.setToolTip("")
        self.lineEdit_8.setAccessibleName("")
        self.lineEdit_8.setInputMask("")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_9.setEnabled(True)
        self.lineEdit_9.setGeometry(QtCore.QRect(210, 80, 51, 31))
        self.lineEdit_9.setToolTip("")
        self.lineEdit_9.setAccessibleName("")
        self.lineEdit_9.setInputMask("")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setEnabled(True)
        self.lineEdit_10.setGeometry(QtCore.QRect(210, 140, 51, 31))
        self.lineEdit_10.setToolTip("")
        self.lineEdit_10.setAccessibleName("")
        self.lineEdit_10.setInputMask("")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setEnabled(True)
        self.lineEdit_7.setGeometry(QtCore.QRect(70, 140, 51, 31))
        self.lineEdit_7.setToolTip("")
        self.lineEdit_7.setAccessibleName("")
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_11.setEnabled(True)
        self.lineEdit_11.setGeometry(QtCore.QRect(140, 140, 51, 31))
        self.lineEdit_11.setToolTip("")
        self.lineEdit_11.setAccessibleName("")
        self.lineEdit_11.setInputMask("")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(90, 200, 171, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(10, 190, 81, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_15.setFont(font)
        self.label_15.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_15.setAcceptDrops(False)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_15.setLineWidth(4)
        self.label_15.setMidLineWidth(2)
        self.label_15.setTextFormat(QtCore.Qt.RichText)
        self.label_15.setScaledContents(False)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setWordWrap(False)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(390, 90, 45, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_16.setFont(font)
        self.label_16.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_16.setAcceptDrops(False)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_16.setLineWidth(4)
        self.label_16.setMidLineWidth(2)
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setScaledContents(False)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setWordWrap(False)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(390, 140, 45, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_17.setFont(font)
        self.label_17.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_17.setAcceptDrops(False)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_17.setLineWidth(4)
        self.label_17.setMidLineWidth(2)
        self.label_17.setTextFormat(QtCore.Qt.RichText)
        self.label_17.setScaledContents(False)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setWordWrap(False)
        self.label_17.setObjectName("label_17")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(440, 90, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(440, 140, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(720, 90, 81, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_19.setFont(font)
        self.label_19.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_19.setAcceptDrops(False)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_19.setLineWidth(4)
        self.label_19.setMidLineWidth(2)
        self.label_19.setTextFormat(QtCore.Qt.RichText)
        self.label_19.setScaledContents(False)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(720, 140, 81, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_21.setFont(font)
        self.label_21.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_21.setAcceptDrops(False)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_21.setLineWidth(4)
        self.label_21.setMidLineWidth(2)
        self.label_21.setTextFormat(QtCore.Qt.RichText)
        self.label_21.setScaledContents(False)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(552, 230, 231, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icone/856332.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(60, 20, 691, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 230, 171, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_3 = QtWidgets.QFrame(self.tab_4)
        self.frame_3.setGeometry(QtCore.QRect(0, 269, 811, 261))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(60, 10, 691, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(10, 60, 45, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_25.setFont(font)
        self.label_25.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_25.setAcceptDrops(False)
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_25.setLineWidth(4)
        self.label_25.setMidLineWidth(2)
        self.label_25.setTextFormat(QtCore.Qt.RichText)
        self.label_25.setScaledContents(False)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setWordWrap(False)
        self.label_25.setObjectName("label_25")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_12.setEnabled(True)
        self.lineEdit_12.setGeometry(QtCore.QRect(68, 67, 251, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setToolTip("")
        self.lineEdit_12.setAccessibleName("")
        self.lineEdit_12.setInputMask("")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_13.setEnabled(True)
        self.lineEdit_13.setGeometry(QtCore.QRect(70, 110, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setToolTip("")
        self.lineEdit_13.setAccessibleName("")
        self.lineEdit_13.setInputMask("")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(10, 110, 45, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_26.setFont(font)
        self.label_26.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_26.setAcceptDrops(False)
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_26.setLineWidth(4)
        self.label_26.setMidLineWidth(2)
        self.label_26.setTextFormat(QtCore.Qt.RichText)
        self.label_26.setScaledContents(False)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setWordWrap(False)
        self.label_26.setObjectName("label_26")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 170, 171, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(10, 160, 81, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_27.setFont(font)
        self.label_27.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_27.setAcceptDrops(False)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_27.setLineWidth(4)
        self.label_27.setMidLineWidth(2)
        self.label_27.setTextFormat(QtCore.Qt.RichText)
        self.label_27.setScaledContents(False)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setWordWrap(False)
        self.label_27.setObjectName("label_27")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(560, 190, 231, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_43 = QtWidgets.QLabel(self.frame_3)
        self.label_43.setGeometry(QtCore.QRect(440, 110, 45, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_43.setFont(font)
        self.label_43.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_43.setAcceptDrops(False)
        self.label_43.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_43.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_43.setLineWidth(4)
        self.label_43.setMidLineWidth(2)
        self.label_43.setTextFormat(QtCore.Qt.RichText)
        self.label_43.setScaledContents(False)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setWordWrap(False)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_3)
        self.label_44.setGeometry(QtCore.QRect(440, 60, 45, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_44.setFont(font)
        self.label_44.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_44.setAcceptDrops(False)
        self.label_44.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_44.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_44.setLineWidth(4)
        self.label_44.setMidLineWidth(2)
        self.label_44.setTextFormat(QtCore.Qt.RichText)
        self.label_44.setScaledContents(False)
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_44.setWordWrap(False)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.frame_3)
        self.label_45.setGeometry(QtCore.QRect(510, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_45.setFont(font)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_3)
        self.label_46.setGeometry(QtCore.QRect(510, 120, 171, 21))
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.frame_3)
        self.label_47.setGeometry(QtCore.QRect(0, 230, 81, 31))
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap(":/icone/Title.png"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.frame_3)
        self.label_48.setGeometry(QtCore.QRect(580, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_48.setFont(font)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.frame_3)
        self.label_49.setGeometry(QtCore.QRect(650, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_49.setFont(font)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frame_3)
        self.label_50.setGeometry(QtCore.QRect(510, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_50.setFont(font)
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.frame_3)
        self.label_51.setGeometry(QtCore.QRect(580, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_51.setFont(font)
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.frame_3)
        self.label_52.setGeometry(QtCore.QRect(650, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_52.setFont(font)
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(370, 190, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icone/Title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        Calculs_Geodisiques.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculs_Geodisiques)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 26))
        self.menubar.setObjectName("menubar")
        Calculs_Geodisiques.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculs_Geodisiques)
        self.statusbar.setObjectName("statusbar")
        Calculs_Geodisiques.setStatusBar(self.statusbar)

        self.retranslateUi(Calculs_Geodisiques)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Calculs_Geodisiques)

    def retranslateUi(self, Calculs_Geodisiques):
        _translate = QtCore.QCoreApplication.translate
        Calculs_Geodisiques.setWindowTitle(_translate("Calculs_Geodisiques", "MainWindow"))
        self.label.setText(_translate("Calculs_Geodisiques", "Paramètres de l\'éllipsoïde"))
        self.lineEdit_1.setPlaceholderText(_translate("Calculs_Geodisiques", "demi grand axe (m)"))
        self.lineEdit_2.setPlaceholderText(_translate("Calculs_Geodisiques", "demi petit axe (m)"))
        self.lineEdit_3.setPlaceholderText(_translate("Calculs_Geodisiques", "invrese de l\'aplatissement"))
        self.lineEdit_4.setPlaceholderText(_translate("Calculs_Geodisiques", "première excentricité "))
        self.label_6.setText(_translate("Calculs_Geodisiques", "e² = "))
        self.label_7.setText(_translate("Calculs_Geodisiques", "1/f = "))
        self.label_8.setText(_translate("Calculs_Geodisiques", "b = "))
        self.label_9.setText(_translate("Calculs_Geodisiques", "a   = "))
        self.pushButton.setText(_translate("Calculs_Geodisiques", "Calculer"))
        self.pushButton_2.setText(_translate("Calculs_Geodisiques", "Clear"))
        self.label_10.setText(_translate("Calculs_Geodisiques", "φ   = "))
        self.lineEdit_5.setPlaceholderText(_translate("Calculs_Geodisiques", "La latitude (gon)"))
        self.label_11.setText(_translate("Calculs_Geodisiques", "M   = "))
        self.label_12.setText(_translate("Calculs_Geodisiques", "N   = "))
        self.label_22.setText(_translate("Calculs_Geodisiques", "Saisir au moins deux paramètres parmis a, b, 1/f, e² pour deduire les autres ."))
        self.label_34.setText(_translate("Calculs_Geodisiques", "φ :  Latitue vous permet de calculer le rayon M et N  après définir deux paramètres del\'éllipsoïde."))
        self.label_35.setText(_translate("Calculs_Geodisiques", "m"))
        self.label_36.setText(_translate("Calculs_Geodisiques", "m"))
        self.label_37.setText(_translate("Calculs_Geodisiques", "Rayon de courbure du méridien"))
        self.label_38.setText(_translate("Calculs_Geodisiques", "Rayon de courbure du premier vertical"))
        self.label_55.setText(_translate("Calculs_Geodisiques", "Exemple des cas pour définir un éllipsoïde :(a,b) , (a,1/f) , (a,e²) ,(b,e²) , (b,1/f) "))
        self.label_39.setText(_translate("Calculs_Geodisiques", "Latitude Isomètrique"))
        self.label_24.setText(_translate("Calculs_Geodisiques", "U   = "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Calculs_Geodisiques", "Calcul Paramètres d\'éllipsoïde"))
        self.label_13.setText(_translate("Calculs_Geodisiques", "φ   = "))
        self.lineEdit_6.setPlaceholderText(_translate("Calculs_Geodisiques", "degré"))
        self.label_14.setText(_translate("Calculs_Geodisiques", "λ   = "))
        self.lineEdit_8.setPlaceholderText(_translate("Calculs_Geodisiques", "minute"))
        self.lineEdit_9.setPlaceholderText(_translate("Calculs_Geodisiques", "seconde"))
        self.lineEdit_10.setPlaceholderText(_translate("Calculs_Geodisiques", "seconde"))
        self.lineEdit_7.setPlaceholderText(_translate("Calculs_Geodisiques", "degré"))
        self.lineEdit_11.setPlaceholderText(_translate("Calculs_Geodisiques", "minute"))
        self.comboBox.setItemText(0, _translate("Calculs_Geodisiques", "1"))
        self.comboBox.setItemText(1, _translate("Calculs_Geodisiques", "2"))
        self.comboBox.setItemText(2, _translate("Calculs_Geodisiques", "3"))
        self.comboBox.setItemText(3, _translate("Calculs_Geodisiques", "4"))
        self.label_15.setText(_translate("Calculs_Geodisiques", "Zone   : "))
        self.label_16.setText(_translate("Calculs_Geodisiques", "X   = "))
        self.label_17.setText(_translate("Calculs_Geodisiques", "Y   = "))
        self.label_19.setText(_translate("Calculs_Geodisiques", "m"))
        self.label_21.setText(_translate("Calculs_Geodisiques", "m"))
        self.pushButton_3.setText(_translate("Calculs_Geodisiques", "Convert to x , y"))
        self.label_20.setText(_translate("Calculs_Geodisiques", "Conversion des coordonnées Géographiques vers les coordonnées Cartographique de Lambert (Maroc)"))
        self.pushButton_5.setText(_translate("Calculs_Geodisiques", "Clear"))
        self.label_23.setText(_translate("Calculs_Geodisiques", "Conversion des coordonnées  Cartographique de Lambert (Maroc) vers des coordonnée Géographiques"))
        self.label_25.setText(_translate("Calculs_Geodisiques", "X  = "))
        self.lineEdit_12.setPlaceholderText(_translate("Calculs_Geodisiques", "abscisse (m)"))
        self.lineEdit_13.setPlaceholderText(_translate("Calculs_Geodisiques", "ordonné (m)"))
        self.label_26.setText(_translate("Calculs_Geodisiques", "Y  = "))
        self.comboBox_2.setItemText(0, _translate("Calculs_Geodisiques", "1"))
        self.comboBox_2.setItemText(1, _translate("Calculs_Geodisiques", "2"))
        self.comboBox_2.setItemText(2, _translate("Calculs_Geodisiques", "3"))
        self.comboBox_2.setItemText(3, _translate("Calculs_Geodisiques", "4"))
        self.label_27.setText(_translate("Calculs_Geodisiques", "Zone   : "))
        self.pushButton_4.setText(_translate("Calculs_Geodisiques", "Convert to φ , λ"))
        self.label_43.setText(_translate("Calculs_Geodisiques", "λ   = "))
        self.label_44.setText(_translate("Calculs_Geodisiques", "φ   = "))
        self.pushButton_6.setText(_translate("Calculs_Geodisiques", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Calculs_Geodisiques", "Conversion des coordonnées"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Calculs_Geodisiques", "Latitude Isomètrique (U)"))
import icone_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculs_Geodisiques = QtWidgets.QMainWindow()
    ui = Ui_Calculs_Geodisiques()
    ui.setupUi(Calculs_Geodisiques)
    Calculs_Geodisiques.show()
    sys.exit(app.exec_())
